// Coordinates are display anchors for named places or corridors, not claimed
// coordinates of explosions. The coordinateAccuracy field controls rendering.
const swodka = n => `https://docs.historyrussia.org/ru/nodes/${n}`;
export const partisanEvents = [
  {id:'voronyansky-rail',title:'Эшелон на линии Полоцк — Молодечно',date:'1944-06-10',dateLabel:'10 июня 1944',location:'Железная дорога Полоцк — Молодечно',coordinates:[28.2,54.9],coordinateAccuracy:'segment',category:'rail',formation:'Бригада им. В. Т. Воронянского',description:'Сводка БШПД сообщает, что бригада под командованием Г. Ф. Покровского пустила под откос эшелон на этой линии.',result:'Точный километр пути в отображаемых материалах не установлен.',source:'Оперативная сводка БШПД № 37 (111)',sourceUrl:swodka('314336-operativnaya-svodka-bshpd-locale-nil-37-111-29-iyunya-1944-g')},
  {id:'dolginovo-zherdyazhye',title:'Засады у Долгинова и Жердяжья',date:'1944-06-22',dateLabel:'10–22 июня 1944',location:'Дороги района Долгиново — Жердяжье',coordinates:[27.55,54.85],coordinateAccuracy:'area',category:'combat',formation:'Бригада им. В. Т. Воронянского',description:'Оперативная сводка описывает действия бригады на шоссейных и грунтовых дорогах этого района.',result:'В сводке указано уничтожение 16 автомашин; отдельные места засад не локализованы.',source:'Оперативная сводка БШПД № 37 (111)',sourceUrl:swodka('314336-operativnaya-svodka-bshpd-locale-nil-37-111-29-iyunya-1944-g')},
  {id:'shatsk',title:'Бой с гарнизоном Шацка',date:'1944-06-29',dateLabel:'29 июня 1944',location:'Шацк и окрестности',coordinates:[27.93,53.18],coordinateAccuracy:'area',category:'combat',formation:'Бригада «Буревестник» (командир Мармулев)',description:'Бригада вступила в бой с отступавшим гарнизоном местечка Шацк.',result:'Сводка БШПД фиксирует бой и потери гарнизона.',source:'Оперативная сводка БШПД № 38 (112)',sourceUrl:swodka('314337-operativnaya-svodka-bshpd-locale-nil-38-112-5-iyulya-1944-g')},
  {id:'lyubcha-garrisons',title:'Гарнизоны Любчи, Верескова и Вселюба',date:'1944-07-05',dateLabel:'2–5 июля 1944',location:'Район Любчи — Верескова — Вселюба',coordinates:[26.0,53.7],coordinateAccuracy:'area',category:'combat',formation:'Бригада им. Ф. Э. Дзержинского (командир Шашкин)',description:'В сводке сообщается о разгроме трёх немецко-полицейских гарнизонов в ходе одной серии действий бригады.',result:'Указаны пленные и захваченные трофеи. Маркер показывает район группы населённых пунктов.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'svisloch-virkov',title:'Засада на большаке Свислочь — Вирков',date:'1944-05-11',dateLabel:'11 мая 1944',location:'Дорога Свислочь — Вирков, Могилёвская область',coordinates:[30.1,53.5],coordinateAccuracy:'segment',category:'combat',formation:'277-й и 278-й партизанские полки',description:'Полки атаковали немецкую колонну из засады на дороге.',result:'Сводка сообщает об уничтожении автомашин и разгроме двух рот противника.',source:'Оперативная сводка БШПД № 29 (103)',sourceUrl:swodka('314328-operativnaya-svodka-bshpd-locale-nil-29-103-16-maya-1944-g')},
  {id:'luninets-baranovichi',title:'Обстрел паровозов на линии Лунинец — Барановичи',date:'1944-05-16',dateLabel:'11–16 мая 1944',location:'Железная дорога Лунинец — Барановичи',coordinates:[26.5,52.7],path:[[26.80,52.25],[26.01,53.13]],coordinateAccuracy:'segment',category:'rail',formation:'Партизаны Полесской области',description:'По сводке, партизаны обстреливали локомотивы из противотанковых ружей на железнодорожной линии.',result:'Сообщается о повреждении паровозов; точные километры пути не названы.',source:'Оперативная сводка БШПД № 31 (105)',sourceUrl:swodka('314330-operativnaya-svodka-bshpd-locale-nil-31-105-26-maya-1944-g')},
  {id:'malkovichi',title:'Засада у станции Малковичи',date:'1944-05-17',dateLabel:'17 мая 1944',location:'Район станции Малковичи',coordinates:[26.8,52.55],coordinateAccuracy:'area',category:'combat',formation:'208-й партизанский полк',description:'Сводка БШПД сообщает о засаде полка на немецкую колонну в районе станции.',result:'В документе указаны потери противника и возвращённое населению имущество.',source:'Оперативная сводка БШПД № 31 (105)',sourceUrl:swodka('314330-operativnaya-svodka-bshpd-locale-nil-31-105-26-maya-1944-g')},
  {id:'porozovo',title:'Бои на дороге Порозово — Новый Двор',date:'1944-05-23',dateLabel:'23 мая 1944',location:'Шоссе Порозово — Новый Двор',coordinates:[24.5,52.7],coordinateAccuracy:'segment',category:'combat',formation:'Бригада им. Чапаева',description:'В сводке отражены действия бригады на шоссе; точный участок не установлен.',result:'Сведения о бое приведены в оперативной сводке.',source:'Оперативная сводка БШПД № 33 (107)',sourceUrl:swodka('314332-operativnaya-svodka-bshpd-locale-nil-33-107-9-iyunya-1944-g')},
  {id:'begoml',title:'Борисовско-Бегомльская партизанская зона',date:'1944-06-08',dateLabel:'Май — июнь 1944',location:'Борисовско-Бегомльская зона',coordinates:[28.2,54.75],coordinateAccuracy:'area',category:'area',formation:'Партизанские бригады зоны',description:'Оперативные документы фиксируют оборонительные бои с карателями и расположение бригад накануне наступления.',result:'Район активности показан обобщённо; границы зоны в этом атласе не реконструированы.',source:'Документы БШПД о Борисовско-Бегомльской зоне',sourceUrl:'https://docs.historyrussia.org/ru/indexes/values/1000619'},
  {id:'senno',title:'Сенненско-Оршанская партизанская зона',date:'1944-06-08',dateLabel:'8–20 июня 1944',location:'Сенненско-Оршанская зона',coordinates:[29.8,54.7],coordinateAccuracy:'area',category:'area',formation:'Бригады Сенненско-Оршанской зоны',description:'Оперативные сводки БШПД описывают бои с карателями и положение соединений в этой зоне.',result:'Место обозначено районом, без точной линии боевых действий.',source:'Документы БШПД о партизанских зонах',sourceUrl:'https://docs.historyrussia.org/ru/indexes/values/1000619'},
  {id:'belunichi',title:'Подрыв рельсов полком «За родину»',date:'1944-06-23',dateLabel:'23 июня 1944',location:'Белыничский район, железная дорога',coordinates:[29.7,54.0],coordinateAccuracy:'area',category:'rail',formation:'122-й партизанский полк «За родину»',description:'Боевое донесение штаба полка посвящено подготовке и проведению операции по подрыву рельсов.',result:'Точное место подрыва не следует из опубликованной карточки документа.',source:'Боевое донесение № 01, НАРБ, ф. 1450, оп. 4, д. 146',sourceUrl:'https://docs.historyrussia.org/ru/nodes/332074-boevoe-donesenie-locale-nil-01-shtaba-122-go-partizanskogo-polka-locale-nil-za-rodinu-locale-nil-voenno-operativnoy-gruppy-pri-belynichskom-podpolnom-raykome-kp-b-b-o-podgotovke-i-provedenii-operatsii-po-podryvu-relsov-na-zheleznoy-doroge-23-iyunya-1944-g'},
  {id:'rail-june',title:'Массовый удар по железным дорогам',date:'1944-06-20',dateLabel:'Ночь 19–20 июня 1944',location:'Коммуникации группы армий «Центр» в Беларуси',coordinates:[28.0,54.0],coordinateAccuracy:'area',category:'rail',formation:'Белорусские партизанские формирования',description:'По указанию БШПД в ночь перед наступлением проводились одновременные подрывы железнодорожных коммуникаций.',result:'Это общая акция; на карте не показаны вымышленные отдельные точки подрывов.',source:'Исследование по документам БШПД',sourceUrl:'https://militera.org/books/pdf/h/sb_osvobozhdenie-belarusi.pdf'},
  {id:'rail-lida',title:'Действия отряда «Боевой» на двух линиях',date:'1944-06-02',dateLabel:'2 июня 1944',location:'Лида — Волковыск; Барановичи — Волковыск',coordinates:[25.3,53.4],coordinateAccuracy:'segment',category:'rail',formation:'Партизанский отряд «Боевой»',description:'Сводка называет обе железнодорожные линии как районы действия отряда.',result:'Точки диверсий в опубликованном фрагменте не уточнены.',source:'Оперативная сводка БШПД № 35 (109)',sourceUrl:swodka('314334-operativnaya-svodka-bshpd-locale-nil-35-109-20-iyunya-1944-g')},
  {id:'dolginovo-roads',title:'Действия бригады «Железняк» на дорогах',date:'1944-06-19',dateLabel:'19–21 июня 1944',location:'Долгиново — Плещеницы и Долгиново — Докшицы',coordinates:[27.8,54.7],coordinateAccuracy:'segment',category:'combat',formation:'Бригада «Железняк»',description:'Оперативная сводка выделяет действия бригады на двух дорогах непосредственно перед наступлением.',result:'Показаны оба дорожных коридора без утверждения точных мест столкновений.',source:'Оперативная сводка БШПД № 37 (111)',sourceUrl:swodka('314336-operativnaya-svodka-bshpd-locale-nil-37-111-29-iyunya-1944-g')},
  {id:'pleshchenitsy',title:'Подрывы автомашин в Плещеницком районе',date:'1944-06-20',dateLabel:'20–21 июня 1944',location:'Шоссейные дороги Плещеницкого района',coordinates:[27.8,54.4],coordinateAccuracy:'area',category:'combat',formation:'Партизанские отряды района',description:'Сводка фиксирует подрывы двух немецких автомашин с личным составом.',result:'Конкретные километры дорог не указаны.',source:'Оперативная сводка БШПД № 37 (111)',sourceUrl:swodka('314336-operativnaya-svodka-bshpd-locale-nil-37-111-29-iyunya-1944-g')},
  {id:'starushki-urechye',title:'Подрыв рельсов на линии Старушки — Уречье',date:'1944-06-23',dateLabel:'Ночь на 23 июня 1944',location:'Железная дорога Старушки — Уречье',coordinates:[27.8,52.9],coordinateAccuracy:'segment',category:'rail',formation:'Партизанская бригада, указанная в сводке БШПД',description:'Сводка сообщает о подрыве рельсов на указанной железнодорожной линии.',result:'В документе названы 97 повреждённых рельсов; точное место внутри участка не установлено.',source:'Оперативная сводка БШПД № 37 (111)',sourceUrl:swodka('314336-operativnaya-svodka-bshpd-locale-nil-37-111-29-iyunya-1944-g')},
  {id:'kozulichi',title:'Налёт на гарнизон в Козуличах',date:'1944-06-14',dateLabel:'До 14 июня 1944',location:'Деревня Козуличи, северо-восточнее Бобруйска',coordinates:[29.5,53.4],coordinateAccuracy:'approximate',category:'combat',formation:'Партизанские отряды, указанные в сводке БШПД',description:'Сводка сообщает о внезапном налёте на немецкий гарнизон в деревне.',result:'Дата самого налёта требует уточнения; здесь указана дата сводки как верхняя граница.',source:'Оперативная сводка БШПД № 34 (108)',sourceUrl:swodka('314333-operativnaya-svodka-bshpd-locale-nil-34-108-14-iyunya-1944-g')},
  {id:'polotsk-dvinsk',title:'Диверсии на линии Полоцк — Двинск',date:'1944-06-29',dateLabel:'Ночь на 29 июня 1944',location:'Железная дорога Полоцк — Двинск',coordinates:[28.2,55.5],coordinateAccuracy:'segment',category:'rail',formation:'Партизанская бригада, названная в сводке БШПД',description:'Оперативная сводка фиксирует действия бригады на железной дороге в ночь на 29 июня.',result:'Показан коридор; точное место диверсии здесь не установлено.',source:'Оперативная сводка БШПД № 39 (113)',sourceUrl:swodka('314338-operativnaya-svodka-bshpd-locale-nil-39-113-8-iyulya-1944-g')},
  {id:'sharkovshchina',title:'Бои на дорогах Шарковщина — Опса — Браслав',date:'1944-06-29',dateLabel:'29 июня — 4 июля 1944',location:'Дороги Шарковщина — Опса — Браслав',coordinates:[27.3,55.55],coordinateAccuracy:'segment',category:'combat',formation:'Бригада им. Жукова',description:'Бригада вела непрерывные бои с отступавшими немецкими частями на названных дорогах.',result:'Сводка сообщает о последующем взаимодействии бригады с частями Красной армии.',source:'Оперативная сводка БШПД № 41 (115)',sourceUrl:swodka('314340-operativnaya-svodka-bshpd-locale-nil-41-115-20-iyulya-1944-g')},
  {id:'voropaevo',title:'Взрыв моста на шоссе Воропаево — Поставы',date:'1944-07-02',dateLabel:'2 июля 1944',location:'Шоссе Воропаево — Поставы',coordinates:[27.2,55.1],coordinateAccuracy:'segment',category:'bridge',formation:'Бригада им. Суворова',description:'Сводка БШПД сообщает о взрыве моста на шоссе.',result:'В документе также говорится об уничтожении трёх автомашин.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'polotsk-klyastitsy',title:'Подрыв двух мостов на шоссе Полоцк — Клястицы',date:'1944-07-03',dateLabel:'3 июля 1944',location:'Шоссе Полоцк — Клястицы',coordinates:[28.8,55.65],coordinateAccuracy:'segment',category:'bridge',formation:'Бригада, упомянутая в сводке БШПД',description:'Сводка сообщает о подрыве двух мостов на шоссе.',result:'Также указано повреждение немецкой техники. Точные места мостов здесь не реконструированы.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'novy-dvor',title:'Налёт на штаб у Нового Двора',date:'1944-07-04',dateLabel:'4 июля 1944',location:'Новый Двор, северо-восточнее Пинска',coordinates:[26.5,52.4],coordinateAccuracy:'approximate',category:'combat',formation:'Пинские партизанские отряды',description:'Отряды атаковали штаб немецкой части при 189-м охранном батальоне.',result:'Сводка сообщает об уничтожении радиостанции и складов.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'soly-gudogay',title:'Повреждение линии у станций Солы и Гудогай',date:'1944-07-06',dateLabel:'Начало июля 1944',location:'Молодечно — Вильно, район станций Солы и Гудогай',coordinates:[26.1,54.4],coordinateAccuracy:'segment',category:'rail',formation:'Партизанские формирования Вилейской области',description:'Партизаны повредили железнодорожное полотно в районе станций.',result:'По сводке, на линии задержались четыре немецких эшелона.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'luninets-pinsk',title:'Атака колонны на дороге Лунинец — Пинск',date:'1944-07-06',dateLabel:'Июль 1944',location:'Дорога Лунинец — Пинск',coordinates:[26.3,52.2],coordinateAccuracy:'segment',category:'combat',formation:'Партизанские отряды Пинской области',description:'На дороге атакована немецкая колонна, двигавшаяся к Пинску.',result:'Сводка сообщает об уничтожении автомашин и захвате вооружения.',source:'Оперативная сводка БШПД № 40 (114)',sourceUrl:swodka('314339-operativnaya-svodka-bshpd-locale-nil-40-114-14-iyulya-1944-g')},
  {id:'new-pogost',title:'Бои у Нового Погоста',date:'1944-07-07',dateLabel:'Начало июля 1944',location:'Район Нового Погоста',coordinates:[27.6,55.45],coordinateAccuracy:'area',category:'combat',formation:'Партизанские формирования Витебской области',description:'Сводка сообщает о боях с отступавшими колоннами противника в районе населённого пункта.',result:'Приведены сведения о пленных и захваченных трофеях.',source:'Оперативная сводка БШПД № 41 (115)',sourceUrl:swodka('314340-operativnaya-svodka-bshpd-locale-nil-41-115-20-iyulya-1944-g')},
];

